### ISSUE TITLE
Room size

### ISSUE THREAD

**Issue by miki5421** [BeatTogether/BeatTogether#14]
Hi, I've noticed that the new update of the mod allows a room up to 5 players only. Just wanted to check is it going to be staying that way, or will it also be increased to 10 players, it's just we usually have quite a few players in Multi.

Thank you

**Comment by Kevman95** [comment]
Hello,

The room size adjustment also happens with the MultiplayerExtensions on PC. You need that as well to go past 5 players.

I do not think it’s updated to 1.13.4 yet. You can find details on their repo by following the links to it on our readme. 

Closing this. You should see this option return when it’s updated.

**Comment by miki5421** [comment]
That's what I thought, that we will need Multiplayer Extensions to get past 5 players.

Thank you for the clarification

**Comment by Kevman95** [comment]
No problem. Do enjoy the mod :) That feature will be back ASAP.
