### ISSUE TITLE
I have no Idea how it was possible but it was hosted on your servers and I want it now lmao 100 player lobby

### ISSUE THREAD

**Issue by 0JXI0** [BeatTogether/BeatTogether#15]
![unknown](https://user-images.githubusercontent.com/56775824/115980192-a9d5d380-a558-11eb-8e3e-71c4f0c3bf95.png)
![Wow](https://user-images.githubusercontent.com/56775824/115980194-aa6e6a00-a558-11eb-8049-e801a1c9149b.png)

**Comment by Kevman95** [comment]
This is done within MultiplayerExtensions.  This allows you to go past 10 players if you edit their configuration file.

Closing issue.
