### ISSUE TITLE
[Feature Request] Ability to host your own BeatTogether instance server

### ISSUE THREAD

**Issue by tompointexe** [BeatTogether/BeatTogether#16]
i think this feature request is pretty much self-explanatory

If possible it would be awsome :)

**Comment by Lauriethefish** [comment]
You can do this. The master server code is located [here](https://github.com/pythonology/BeatTogether.MasterServer) and you can run it yourself.

Instructions aren't available at the moment, but you can totally do it.

**Comment by Kevman95** [comment]
Yeah, Please refer to above. It runs in docker containers so its quite simple if you know your way around it.
