### ISSUE TITLE
Add to BeatMods/ModAssistant

### ISSUE THREAD

**Issue by MightiestTaco** [BeatTogether/BeatTogether#18]
PLEASE add to BeatMods so it's A) easier to access B) can be downloaded and installed with ModAssistant. I know this isn't an "Issue" but I didn't know where to put it. Thanks!

**Comment by Kevman95** [comment]
The mod is already submitted to approval for BeatMods. There isn't much more we can do other than pester BeatMods to approve it.

In the meantime, you can use our manual install instructions to install the mod.
