### ISSUE TITLE
Lobby Code is blank for clients

### ISSUE THREAD

**Issue by roydejong** [BeatTogether/BeatTogether#19]
When a player joins a BeatTogether-hosted game, they cannot see the Lobby Code (it's an empty string).

This only applies to players that join the game, not the host. 

This problem is caused by V3 protocol changes to certain Master Server messages that haven't been properly implemented by BeatTogether yet. This results in the client not receiving the lobby code when they're connecting to a server (even if the client entered it themselves, it's expected to be in the connect message).

I'm working on the necessary changes, so using this issue to track it for now.

**Comment by Kevman95** [comment]
Going to close this issue as it is moot now considering our work on 1.17.1.
