### ISSUE TITLE
Error cfr-9 while creating a new server

### ISSUE THREAD

**Issue by HugWolf** [BeatTogether/BeatTogether#20]
Beat Saber version 1,16,4
Beat Together version: PC v1.1.3

Error cfr-9 while creating a new server, but I see server status is ONLINE.
How can I solve it?

Tried some steps from this topic https://steamcommunity.com/app/620980/discussions/2/4420805388059415190/ but it doesn't work for me

**Comment by Oikio** [comment]
Same issue here, thank you for the plugin btw!

**Comment by PopeHax** [comment]
@Oikio @HugWolf 

Beat Together PC v1.1.3 is only compatible with BS v1.16.2 as stated in the features, Beat together has not been updated yet to support BS v1.16.4

Hopefully we will hear something soon.

**Comment by Oikio** [comment]
Thank you for the response, clear now.

**Comment by Kevman95** [comment]
The plugin hasn't bee updated. 

Join our discord server for future updates: https://discord.com/invite/gezGrFG4tz
