### ISSUE TITLE
Beatsaber V 1.17.1 release

### ISSUE THREAD

**Issue by JohSchillerEmnify** [BeatTogether/BeatTogether#23]
Hi, as you've maybe heard v1.17.1 was released about 20 days ago, This breaks mod support _again_ like always, can i assist you with anything regarding the necessary updates to Beattogether?

**Comment by Kevman95** [comment]
This is already being worked on for the latest version of Beat Saber. The reason it has been broken for a time is due to MP changes that Beat Games implemented. It will be available soon.

Updates get posted here: https://discord.com/invite/gezGrFG4tz

**Comment by queengooborg** [comment]
By updates, do you mean news posts or prereleases?  If it's the latter, would you be willing to post them here on the GitHub repo as well?

**Comment by Kevman95** [comment]
All info is in Discord.

**Comment by queengooborg** [comment]
Right, but I'm asking if it's just information, or if there are alpha/beta releases, and if so then it'd be great if you could create a prerelease here on GitHub.  I don't use Discord.  :P

**Comment by Kevman95** [comment]
There is no releases for latest yet. All news in in the Discord.
