### ISSUE TITLE
custom tracks not showing up in the server creator on latest version.

### ISSUE THREAD

**Issue by LK1308** [BeatTogether/BeatTogether#26]
Hey y'all, love what you guys do and have been really hyped to see the update for BeatTogether. I'm having a issue with the mod not showing up in mod settings and when launching a private server with the BeatTogether setting in multiplayer selected I can't see any custom tracks. My friend is having the same issue and we don't know what could be causing it. we installed the mod properly in the plugins folder in the beatsaber directory from steam and it does show up in the multiplayer menu. would love to see if anyone has a fix or knows if I've just messed up my install some how. Additionally I had done a whole fresh reinstall of beatsaber just to see if that would fix anything but it didn't. again really would appreciate any help someone could give me.

**Comment by Kevman95** [comment]
For customs to appear you must be connecting to our servers, and have MultiplayerExtensions for PC.

Refer to our custom song support instructions in the readme.
