### ISSUE TITLE
not connecting to servers

### ISSUE THREAD

**Issue by jonahplayscello** [BeatTogether/BeatTogether#29]
it won't let me connect to the server it just says could not connect to the server check your internet connection and try again(CFR-9) 
and i have a good internet connection

**Comment by Kevman95** [comment]
It's not available for 1.19.0 yet. You need to downgrade. 

Please join our Discord for more assistance which is linked on readme.

**Comment by jonahplayscello** [comment]
what version do I need to downgrade to?

**Comment by Kevman95** [comment]
1.18.3
