### ISSUE TITLE
Buggy Players / Not In Sync Players

### ISSUE THREAD

**Issue by DarkeyPoo** [BeatTogether/BeatTogether#3]
Sometimes the players will start bugging out, and their arms will start flailing uncontrollably. It usually happens to the player that joins another player's custom server. Also, the players sometimes lag and get put into the match a little before or after others when starting a custom song (don't know about built-in yet). This bug causes a delay that when in-game, shows the other players playing a different part of the song than you (10 to 20 seconds behind or ahead) and the end also shows only you on the leaderboard. There is no one else on the leaderboard so you are always number one, even if no one else loses. Hope this helps! I'll keep testing for you guys cause I got a quest and a Rift S! (That's how I am testing)

**Comment by Kevman95** [comment]
Hello,

This is because you keep getting tossed onto a relay, since your on the same network.

Our relay implementation is quite early. We will eventually be looking into solutions and fixes for it. So we are aware there could be some issues.

Thanks for the report.

**Comment by DarkeyPoo** [comment]
Would this happen to be fixed by a VPN if the person on rift did that?

**Comment by Kevman95** [comment]
You can try a VPN or a hotspot to see if results better. However the real fix will come from us.

**Comment by DarkeyPoo** [comment]
> You can try a VPN or a hotspot to see if results better. However the real fix will come from us.

Great thanks!
