### ISSUE TITLE
-

### ISSUE THREAD

**Issue by KatDevsGames** [BeatTogether/BeatTogether#32]

**Comment by Kevman95** [comment]
This seems like a problem for JDfixer. Not BeatTogether.

**Comment by KatDevsGames** [comment]
It's going to be a problem for BeatTogether when people realize they can do this and the JDFixer people don't care because you're not ScoreSaber. 🙂

**Comment by Kevman95** [comment]
@KatDevsGames Again, you need to report this issue to JDfixer. We do not handle issues that other plug-ins create.

**Comment by KatDevsGames** [comment]
Disregard. I thought yall were BeatLeader and not some random other plugin I've never heard of. Bye.
