### ISSUE TITLE
Not available through Mod Assistant

### ISSUE THREAD

**Issue by Snailedlt** [BeatTogether/BeatTogether#36]
The README.md file suggests installing through Mod Assistant, but this plugin isn't available through the Mod Assistant.
![image](https://user-images.githubusercontent.com/43886029/177014407-1ee6f894-2926-4013-82c8-d1488f617ee8.png)
![image](https://user-images.githubusercontent.com/43886029/177014474-f0309864-3a19-43b4-9d31-4124a9de5809.png)

Either update the README.md or add it to the Mod Assistant

**Comment by Kevman95** [comment]
Use the manuals install instructions.
