### ISSUE TITLE
Lag and glitching

### ISSUE THREAD

**Issue by hemilm** [BeatTogether/BeatTogether#4]
Hey dude this mod has some issues with crashing of the servers. Most likely it is because it interferes a bit with the multiplayer custom songs extension. That mod let's players play custom songs together as well as downloads them. Generally the lag and server issues will happen right after trying to load the song or during the actual song start.

**Comment by Kevman95** [comment]
Hello,

This is not a specific server issue as the servers are running fine. Any lobby lockups or issues is due to the MultiplayerExtensions plugin with crossplay. Our suggestion is to report these issues to them so they can investigate it and solve them.

Going to close this issue.
