### ISSUE TITLE
Feature request: allow each player to select their own difficulty for a map

### ISSUE THREAD

**Issue by queengooborg** [BeatTogether/BeatTogether#40]
I like to play Beat Saber multiplayer with others to show them cool maps I've found, or to have fun and work out together.  However, most of those I play with are not quite as skilled/experienced with the game as I am (I started playing Beat Saber since the initial release), so often times I have to switch to a lower difficulty, if I'm able to (many of the maps I have only have Expert+ or Expert++).

I think it would be cool if each player in a multiplayer lobby could select their own map difficulty, so that I could enjoy a crazy Lawless Expert+++ map, while a friend of mine who just started playing yesterday can enjoy a Normal map.  I know that this may be weird for the scoring system, since less notes = less blocks, but as I mentioned before, we don't play to compete anyways.

**Comment by Kevman95** [comment]
This is in the works. In the meantime however till that is ready, we recommend the no fail option as a backup.

**Comment by queengooborg** [comment]
That's awesome!  Looking forward to it, thank you for the info!

**Comment by ILazyVibesI** [comment]
I would like to know if this is still in the works.

**Comment by crisflashin** [comment]
Me too ! i really wish this feature come true, it will be great!

**Comment by Kevman95** [comment]
It is definitely still in the works. Our server supports it, we just have to add it so it can be enabled on the client.

This mod is a volunteer effort so a lot of things have gotten in the way as of late. Its definitely something we plan to do though!

**Comment by gautamg795** [comment]
@Kevman95 would you be open to leaving the issue opened until it's released on the client? would love to just have a place to check in on the progress of the task!
