### ISSUE TITLE
[Bug]: Compatibility with 1.3x 

### ISSUE THREAD

**Issue by Naeaeaeaeae** [BeatTogether/BeatTogether#46]
### Describe the bug

There is no compatible Version in ModAssistant 

### Steps to reproduce

Open ModAssistant

### Expected Behavior

Compatibility?

### Actual Behavior

No Compatibility?

### Game Version

1.3x

### Mod Version

up to date

### Additional context

I thought of what I read in your comments that the mod should be compatible with the newer versions, but ModAssistant doesn't show you any available versions.

(https://github.com/BeatTogether/BeatTogether/pull/44)

**Comment by Kevman95** [comment]
Hey,

It is coming. These things take time. The latest version is in testing via our Patreon. (Also a link to this if you want: https://www.patreon.com/BeatTogether)

Currently for PC it is 1.29.1 supported. For quest it is 1.28 supported. Both can crossplay.

You can join our discord to follow us for future updates as well: https://discord.com/invite/gezGrFG4tz
